### ISSUE TITLE
Can you tell me how to control it in Python?

### ISSUE THREAD

**Issue by haiyangder** [simondlevy/MulticopterSim#139]

**Comment by simondlevy** [comment]
1. Make sure you're using the Socket module (double-click use_socket.bat)
2. Clone [Hackflight ](https://github.com/simondlevy/Hackflight)
3. Run Hackflight/extras/python/hackflight.py 

You'll need some kind of game controller (Xbox, PS4, etc.) to fly.

**Comment by simondlevy** [comment]
I'll try and add keyboard control for the hackflight.py script, too.
