### ISSUE TITLE
I ran MulticopterSim, why it keeps going up, and how to fix it. I look forward to hearing from you!

### ISSUE THREAD

**Issue by haiyangder** [simondlevy/MulticopterSim#143]
I don't know what needs to be modified. Could you help me

**Comment by haiyangder** [comment]
can you tell me your email

**Comment by simondlevy** [comment]
I tried to answer your question here: https://github.com/simondlevy/MulticopterSim/issues/139

If those directions don't help, try me at simon.d.levy@gmail.com
