### ISSUE TITLE
Joystick question

### ISSUE THREAD

**Issue by bhowiebkr** [simondlevy/MulticopterSim#149]
Cool project, 

How do you have joysticks implemented into ue4? I’ve been trying to get my FrSky taranis (running EdgeTX firmware) through the raw input plugin. 

I’ve been able to get it running through python using the winmm.dll using some code I found here: https://stackoverflow.com/questions/60309652/how-to-get-usb-controller-gamepad-to-work-with-python

I see that my product and vendor ids differ to the ones you are using in your source files for this project.
![image](https://user-images.githubusercontent.com/904170/183313900-9f8a6c91-1391-4bf5-9a64-a7ce263311eb.png)

**Comment by simondlevy** [comment]
Thanks, Bryan!  I too struggled with various ways of getting joystick / game controller / RC transmitter input into UE4/5, and settled on writing my own standalone C++ class to do it.  Most of the relevant code (product ID detection, axis polling) is in the [header file](https://github.com/simondlevy/MultiSim/blob/master/Source/MultiSim/Joystick.h), with the [.cpp file](https://github.com/simondlevy/MultiSim/blob/master/Source/MultiSim/Joystick.cpp) containing just the Windows code for reading the axes and buttons.   When I get a new game controller, I do the following:

(1) Get the device's product ID (which you appear to have done, getting 0x4f54)
(2) Use the Game Controller setup dialog to map the device's axes.
(3) Add a symbolic constant to the product IDs in the header file.
(4) Add a case statement for the product IDto the switch in the poll() method.

I've attached a couple of screenshots illustrating this process.  Let me know if you run into any trouble.

![productid](https://user-images.githubusercontent.com/6766537/183317284-c8ff04bc-bcaa-41c9-a32e-f5470d12869c.png)


![switch](https://user-images.githubusercontent.com/6766537/183317286-b7a61465-cb75-4517-a119-0c0ea62577e8.png)

**Comment by bhowiebkr** [comment]
Cool, Yeah I’ll do it through the win32 api and forget about trying to get unreal to read it correctly. I had the same issues when trying to get a PS4 controller to work in unreal for a hexapod simulator and had to rely on third party intermediary apps to turn it into a different generic joystick so unreal would see it on the raw input plugin. 

From the looks of it (have not tried) but the ability to remap input axis in ue4/5 look to be easy and even blueprintable. Probably something to leave till later and build a whole UMG interface to make the axis mapping easier.

**Comment by bhowiebkr** [comment]
FYI I’m running UE5.0.3 and VS2022 and didn’t have to do anything special to get them working together. Even your MultiSim project compiled and ran correct. Python server runs as well and talks to ue5 for me during play. It doesn’t pick up my FrSky taranis though from what I can tell. I tried changing the PID to the id that mine shows up in windows (0x4f54). The difference in PID is likely attributed to the fact that I’m running edgetx.org firmware instead of OpenTX on the taranis and they wanted to differentiate the firmwares. 

I’m not sure how the devs that built Liftoff did it because it shows up correctly. Possibly they query all available joysticks and save the final joystick config mapping in an ini file somewhere.

**Comment by simondlevy** [comment]
Cool, maybe I should give UE5+VS2022 another try!
