### ISSUE TITLE
Quick question on physics

### ISSUE THREAD

**Issue by yhyu13** [simondlevy/MulticopterSim#5]
Just a quick question. In [this line](https://github.com/simondlevy/HackflightSim/blob/b5aa3169199e7cce0e234a73c89f6ad71259ebf9/Source/HackflightSim/HackflightSimPawn.cpp#L288), should it be FVector(x,y,z) instead(as they are the result of rotational matrix times (0,0,1))? I am not sure I understand why it's necessary to negate the (x,y) components of the thrust in the inertial frame?

PS: I haven't run your project in UE editor yet, just skimming through your code. I'm looking forward to writing my drone simulation in UE as well. You're pretty good, @simondlevy!

**Comment by simondlevy** [comment]
Sorry it took me so long to answer this!  Check out the [new version](https://github.com/simondlevy/MulticopterSim/blob/master/Source/MulticopterSim/hackflight/BuiltinPhysics.cpp#L65-L79) for an explanation.
